export function createAdminUI(env){
  const {state,api,$,$$,esc,ico,toast,openModal,closeModal,dateFull,download}=env;
  let tab='users',cache={users:[],roles:[],teams:[],permissions:[],sessions:[],logs:[]},sequence=0,logFilters={q:'',result:'',from:'',to:'',page:1};
  const can=p=>(state.context?.permissions||[]).includes(p);
  const opts=(items,value,empty=null)=>`${empty!==null?`<option value="">${esc(empty)}</option>`:''}${items.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?'selected':''}>${esc(x.name||x.label||x.username||x.id)}</option>`).join('')}`;
  const field=(label,name,value='',extra='')=>`<label class="form-field">${esc(label)}<input name="${esc(name)}" value="${esc(value)}" ${extra}></label>`;
  const check=(label,name,checked,hint='')=>`<label class="v2-check"><input type="checkbox" name="${esc(name)}" ${checked?'checked':''}><span>${esc(label)}${hint?`<small>${esc(hint)}</small>`:''}</span></label>`;
  const error=err=>`<div class="form-error" role="alert">${esc(err.message||err)}</div>`;
  const scopeName=value=>({own:'Mes demandes',team:'Mes équipes',all:'Toutes les demandes'})[value]||value;
  function availableTabs(){return [['users','Utilisateurs','admin.users'],['roles','Rôles & permissions','admin.roles'],['teams','Équipes','admin.users'],['sessions','Sessions','admin.users'],['logs','Journal d’audit','admin.logs']].filter(([, ,permission])=>can(permission));}
  function render(){const tabs=availableTabs();if(!tabs.some(([id])=>id===tab))tab=tabs[0]?.[0];$('#main').innerHTML=`<div class="page-heading"><div><div class="eyebrow">Administration de Vigie</div><h1>Comptes & accès</h1><p>Les droits et les actions sont associés à chaque compte.</p></div></div><div class="v2-tabs" role="group" aria-label="Administration">${tabs.map(([id,label])=>`<button class="v2-tab ${tab===id?'active':''}" data-admin-tab="${id}">${label}</button>`).join('')}</div><div id="admin-content"><div class="v2-empty" role="status">Chargement…</div></div>`;load();}
  async function load(){const seq=++sequence;try{
    const route={users:'users',roles:'roles',teams:'teams',sessions:'sessions',logs:'logs'}[tab];if(!route){$('#admin-content').innerHTML='<div class="v2-empty">Votre compte ne dispose pas d’un accès à cette administration.</div>';return;}
    const query=tab==='logs'?`?${new URLSearchParams(Object.entries(logFilters).filter(([,v])=>v!==''))}`:'';
    const response=await api(`/api/admin/${route}${query}`);if(seq!==sequence||state.view!=='admin')return;cache[tab]=response.items||[];
    if(tab==='users')usersView();if(tab==='roles')rolesView();if(tab==='teams')teamsView();if(tab==='sessions')sessionsView();if(tab==='logs')logsView(response);
  }catch(err){if($('#admin-content')&&seq===sequence)$('#admin-content').innerHTML=`${error(err)}<button class="button" data-admin-action="reload">Réessayer</button>`;}}
  function table(headers,rows){return `<section class="panel"><div class="table-wrap"><table class="v2-table"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>${rows.length?'':'<p class="v2-empty">Aucun élément à afficher.</p>'}</section>`;}
  function usersView(){$('#admin-content').innerHTML=`<div class="v2-title-row"><p class="muted">${cache.users.length} compte${cache.users.length>1?'s':''} · un rôle métier par personne</p><button class="button primary" data-admin-action="new-user">${ico('plus')}Créer un utilisateur</button></div>${table(['Utilisateur','Rôle & portée','Conception','État','Actions'],cache.users.map(user=>`<tr><td><span class="v2-name">${esc(user.name)}</span><small>${esc(user.username)}</small><small>Dernière connexion : ${esc(dateFull(user.last_login_at))}</small></td><td>${esc(user.role_name||user.role_id)}<small>${esc(scopeName(user.scope))}</small></td><td>${user.permissions?.includes('site.edit')?'<span class="badge status-progress">Conception</span> ':''}${user.permissions?.includes('site.publish')?'<span class="badge status-open">Publication</span>':''}${!user.permissions?.includes('site.edit')&&!user.permissions?.includes('site.publish')?'—':''}</td><td><span class="badge ${user.active?'status-progress':'status-closed'}">${user.active?'Actif':'Désactivé'}</span></td><td><div class="v2-toolbar"><button class="button small" data-admin-edit-user="${esc(user.id)}">Modifier</button><button class="button small" data-admin-revoke="${esc(user.id)}">Révoquer les sessions</button></div></td></tr>`))}<p class="v2-hint" style="margin-top:16px">Désactiver un compte conserve son historique. Les changements de droits invalident ses sessions. Le dernier administrateur actif est protégé.</p>`;}
  function rolesView(){$('#admin-content').innerHTML=`<div class="v2-title-row"><p class="muted">Permissions métier et capacités de conception</p><button class="button primary" data-admin-action="new-role">${ico('plus')}Créer un rôle</button></div><div class="v2-grid">${cache.roles.map(role=>`<section class="v2-card"><h3>${esc(role.name)}</h3><p>${esc(role.description||'Rôle personnalisé')}</p><div class="tag-list">${(role.permissions||[]).map(p=>`<span>${esc(permissionLabel(p))}</span>`).join('')}</div><div class="v2-card-footer"><small class="muted">${role.builtin?'Rôle intégré':'Rôle personnalisé'} · version ${role.version}</small><button class="button small" data-admin-edit-role="${esc(role.id)}">${role.id==='admin'?'Consulter':'Modifier'}</button></div></section>`).join('')}</div>`;}
  function teamsView(){$('#admin-content').innerHTML=`<div class="v2-title-row"><p class="muted">Les équipes déterminent le périmètre de consultation.</p><button class="button primary" data-admin-action="new-team">${ico('plus')}Créer une équipe</button></div>${table(['Équipe','Identifiant','Action'],cache.teams.map(team=>`<tr><td><span class="v2-name">${esc(team.name)}</span></td><td>${esc(team.id)}</td><td><button class="button small" data-admin-edit-team="${esc(team.id)}">Renommer</button></td></tr>`))}`;}
  function sessionsView(){$('#admin-content').innerHTML=`<div class="v2-title-row"><p class="muted">Sessions actives · expiration après 30 minutes d’inactivité ou 8 heures.</p><button class="button" data-admin-action="reload">${ico('refresh')}Actualiser</button></div>${table(['Compte','Début de session','Dernière activité','Expiration','Action'],cache.sessions.map(session=>`<tr><td><span class="v2-name">${esc(session.username)}</span></td><td>${esc(dateFull(session.created_at))}</td><td>${esc(dateFull(session.last_seen_at))}</td><td>${esc(dateFull(session.expires_at))}</td><td><button class="button small" data-admin-revoke="${esc(session.user_id)}">Révoquer les sessions du compte</button></td></tr>`))}`;}
  function logsView(response){$('#admin-content').innerHTML=`<form id="admin-log-filters" class="v2-form-inline" style="margin-bottom:18px"><label class="form-field">Recherche<input name="q" value="${esc(logFilters.q)}" placeholder="Action, compte, ressource…"></label><label class="form-field">Résultat<select name="result"><option value="">Tous</option><option value="success" ${logFilters.result==='success'?'selected':''}>Réussite</option><option value="denied" ${logFilters.result==='denied'?'selected':''}>Refus</option><option value="failure" ${logFilters.result==='failure'?'selected':''}>Échec</option></select></label>${field('À partir du','from',logFilters.from,'type="date"')}${field('Jusqu’au','to',logFilters.to,'type="date"')}<button class="button primary" type="submit">Filtrer</button><button class="button" type="button" data-admin-action="export-logs">Exporter CSV</button></form>${table(['Date','Auteur','Action','Ressource','Résultat','Détails'],cache.logs.map(log=>`<tr><td>${esc(dateFull(log.created_at))}</td><td>${esc(log.actor_name||'Non authentifié')}</td><td><span class="v2-name">${esc(log.action)}</span><small>${esc(log.workspace)}</small></td><td>${esc(log.target||'—')}</td><td><span class="badge ${log.result==='success'?'status-progress':'status-waiting'}">${esc(log.result)}</span></td><td><div class="v2-code">${esc(typeof log.details==='object'?JSON.stringify(log.details,null,2):log.details||'—')}</div></td></tr>`))}<div class="v2-title-row" style="margin-top:15px"><p class="v2-hint">${response.total??cache.logs.length} événement${response.total===1?'':'s'} · page ${response.page||logFilters.page}</p><div class="v2-toolbar"><button class="button small" data-admin-page="-1" ${logFilters.page<=1?'disabled':''}>Précédente</button><button class="button small" data-admin-page="1" ${(response.page||logFilters.page)*(response.page_size||50)>=(response.total||0)?'disabled':''}>Suivante</button></div></div>`;}
  async function refs(){const results=await Promise.allSettled([api('/api/admin/roles'),api('/api/admin/teams'),api('/api/admin/permissions')]);for(let i=0;i<results.length;i++)if(results[i].status==='fulfilled')cache[['roles','teams','permissions'][i]]=results[i].value.items||[];}
  function permissionLabel(id){return cache.permissions.find(p=>p.id===id)?.label||({'requests.read':'Consulter les demandes','requests.create':'Créer des demandes','requests.comment':'Commenter','requests.update':'Modifier le suivi','requests.assign':'Affecter','requests.status':'Changer le statut','requests.close':'Clôturer','requests.reopen':'Rouvrir','requests.move':'Corriger les rattachements','requests.import':'Importer','requests.export':'Exporter','admin.users':'Administrer les comptes','admin.roles':'Administrer les rôles','admin.logs':'Consulter le journal','admin.backup':'Sauvegarder','site.edit':'Concevoir le site','site.publish':'Publier le site'})[id]||id;}
  async function userModal(id){await refs();const user=cache.users.find(u=>u.id===id)||{active:true,role_id:'contributor',scope:'team',team_ids:['general']};const edit=Boolean(id);openModal({title:edit?'Modifier le compte':'Créer un utilisateur',subtitle:'Compte Vigie · un rôle métier et des capacités de conception complémentaires.',wide:true,content:`<form id="admin-user-form" data-id="${esc(id||'')}" class="modal-content"><div class="modal-form-grid">${field('Nom affiché','name',user.name,'required maxlength="150"')}${field('Identifiant de connexion','username',user.username,'required autocomplete="off" maxlength="100"')}</div>${field(edit?'Nouveau mot de passe (laisser vide pour conserver)':'Mot de passe initial','password','',`type="password" autocomplete="new-password" minlength="12" ${edit?'':'required'}`)}<p class="v2-hint">Au moins 12 caractères. Transmettez le mot de passe à la personne par votre canal habituel.</p><div class="modal-form-grid"><label class="form-field">Rôle métier<select name="role_id">${opts(cache.roles,user.role_id)}</select></label><label class="form-field">Périmètre des demandes<select name="scope"><option value="own" ${user.scope==='own'?'selected':''}>Mes demandes uniquement</option><option value="team" ${user.scope==='team'?'selected':''}>Mes demandes et mes équipes</option><option value="all" ${user.scope==='all'?'selected':''}>Toutes les demandes</option></select></label></div><fieldset class="v2-permission-group"><legend>Équipes</legend><div class="v2-check-grid">${cache.teams.map(team=>check(team.name,`team:${team.id}`,(user.team_ids||[]).includes(team.id))).join('')}</div></fieldset><fieldset class="v2-permission-group"><legend>Capacités complémentaires</legend><div class="v2-permission-grid">${check('Concevoir le site','site_edit',user.site_edit,'Personnaliser le brouillon, les formulaires et les pages.')}${check('Publier le site','site_publish',user.site_publish,'Rendre un brouillon visible aux utilisateurs autorisés.')}</div></fieldset>${check('Compte actif','active',user.active,'Un compte désactivé ne peut plus se connecter.')}<div id="admin-modal-error"></div></form>`,footer:`<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="admin-user-form">${edit?'Enregistrer':'Créer le compte'}</button>`});}
  async function roleModal(id){await refs();const role=cache.roles.find(r=>r.id===id)||{name:'',description:'',permissions:[]};const immutable=id==='admin';const permissions=cache.permissions.length?cache.permissions:Object.keys({'requests.read':1,'requests.create':1,'requests.comment':1,'requests.update':1,'requests.assign':1,'requests.status':1,'requests.close':1,'requests.reopen':1,'requests.move':1,'requests.import':1,'requests.export':1,'site.edit':1,'site.publish':1}).map(id=>({id,label:permissionLabel(id)}));openModal({title:immutable?'Rôle administrateur':id?'Modifier le rôle':'Créer un rôle',subtitle:immutable?'Le rôle système garantit la continuité de l’administration.':'Les changements s’appliquent à tous les utilisateurs de ce rôle.',wide:true,content:`<form id="admin-role-form" data-id="${esc(id||'')}" data-version="${role.version||0}" class="modal-content">${field('Nom du rôle','name',role.name,`required maxlength="100" ${immutable?'disabled':''}`)}<label class="form-field">Description<textarea name="description" maxlength="1000" ${immutable?'disabled':''}>${esc(role.description)}</textarea></label><div class="v2-check-grid">${permissions.filter(p=>immutable||!p.id.startsWith('admin.')).map(p=>`<label class="v2-check"><input type="checkbox" name="permission:${esc(p.id)}" ${(role.permissions||[]).includes(p.id)?'checked':''} ${immutable?'disabled':''}><span>${esc(p.label||permissionLabel(p.id))}</span></label>`).join('')}</div><p class="v2-hint">L’import exige aussi un périmètre « Toutes les demandes ». Les permissions d’administration sont réservées au rôle système.</p><div id="admin-modal-error"></div></form>`,footer:`<button class="button" data-action="close-modal">${immutable?'Fermer':'Annuler'}</button>${immutable?'':'<button class="button primary" type="submit" form="admin-role-form">Enregistrer le rôle</button>'}`});}
  function teamModal(id){const team=cache.teams.find(t=>t.id===id)||{};openModal({title:id?'Renommer l’équipe':'Créer une équipe',content:`<form id="admin-team-form" data-id="${esc(id||'')}" class="modal-content">${field('Nom de l’équipe','name',team.name,'required maxlength="100"')}<div id="admin-modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="admin-team-form">Enregistrer</button>'});}
  function revokeModal(id){const self=state.context.actor.id===id;openModal({title:'Révoquer les sessions',subtitle:self?'Votre session actuelle sera également fermée.':'Le compte devra se reconnecter pour accéder à Vigie.',content:`<form id="admin-revoke-form" data-id="${esc(id)}" class="modal-content"><p>Confirmer la fermeture de toutes les sessions actives de ce compte ?</p><div id="admin-modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button danger" type="submit" form="admin-revoke-form">Révoquer les sessions</button>'});}
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const run=async()=>{if(b.dataset.adminTab){tab=b.dataset.adminTab;render();}if(b.dataset.adminEditUser)await userModal(b.dataset.adminEditUser);if(b.dataset.adminEditRole)await roleModal(b.dataset.adminEditRole);if(b.dataset.adminEditTeam)teamModal(b.dataset.adminEditTeam);if(b.dataset.adminRevoke)revokeModal(b.dataset.adminRevoke);if(b.dataset.adminPage){logFilters.page+=Number(b.dataset.adminPage);load();}switch(b.dataset.adminAction){case'new-user':await userModal();break;case'new-role':await roleModal();break;case'new-team':teamModal();break;case'reload':load();break;case'export-logs':download(`/api/admin/logs/export?${new URLSearchParams(Object.entries(logFilters).filter(([,v])=>v!==''))}`,'vigie-journal.csv');break;}};run().catch(err=>toast(err.message,true));});
  document.addEventListener('submit',async event=>{const f=event.target;if(!f.id.startsWith('admin-'))return;event.preventDefault();const fd=new FormData(f),data=Object.fromEntries(fd);if(f.id==='admin-log-filters'){logFilters={...data,page:1};load();return;}const button=$(`[form="${f.id}"][type="submit"]`);if(button)button.disabled=true;try{
    if(f.id==='admin-user-form'){const body={username:data.username,name:data.name,role_id:data.role_id,scope:data.scope,team_ids:[...fd.keys()].filter(k=>k.startsWith('team:')).map(k=>k.slice(5)),active:fd.has('active'),site_edit:fd.has('site_edit'),site_publish:fd.has('site_publish')};if(data.password)body.password=data.password;await api(`/api/admin/users${f.dataset.id?`/${encodeURIComponent(f.dataset.id)}`:''}`,{method:f.dataset.id?'PATCH':'POST',body});}
    if(f.id==='admin-role-form')await api(`/api/admin/roles${f.dataset.id?`/${encodeURIComponent(f.dataset.id)}`:''}`,{method:f.dataset.id?'PATCH':'POST',body:{name:data.name,description:data.description,permissions:[...fd.keys()].filter(k=>k.startsWith('permission:')).map(k=>k.slice(11)),...(f.dataset.id?{version:Number(f.dataset.version)}:{})}});
    if(f.id==='admin-team-form')await api(`/api/admin/teams${f.dataset.id?`/${encodeURIComponent(f.dataset.id)}`:''}`,{method:f.dataset.id?'PATCH':'POST',body:{name:data.name}});
    if(f.id==='admin-revoke-form')await api(`/api/admin/users/${encodeURIComponent(f.dataset.id)}/revoke-sessions`,{method:'POST',body:{}});
    if(f.id!=='admin-revoke-form'){const context=await api('/api/context');state.context={...state.context,...context};const actorName=$('.sidebar-footer .actor-name');if(actorName)actorName.textContent=context.actor.name;}closeModal();toast(f.id==='admin-revoke-form'?'Les sessions du compte ont été révoquées.':'Les modifications ont été enregistrées.');load();
  }catch(err){if($('#admin-modal-error'))$('#admin-modal-error').innerHTML=error(err);else toast(err.message,true);}finally{if(button?.isConnected)button.disabled=false;}});
  return {render};
}
