export function createDesigner(env){
  const {state,api,$,$$,esc,ico,toast,openModal,closeModal,dateFull}=env;
  const nativeFields={title:'Intitulé',channel:'Canal',requester:'Demandeur',requester_email:'E-mail du demandeur',description:'Description',priority:'Priorité',application:'Application',category:'Catégorie',environment:'Environnement',ritm:'RITM',assignee:'Affectation',status:'Statut'};
  const navLabels={active:'À traiter',all:'Toutes les demandes',mine:'Mes demandes',unassigned:'Sans affectation',waiting:'En attente',alerts:'Réponses à examiner',closed:'Demandes closes',reporting:'Pilotage',imports:'Imports & rapprochements'};
  const types={text:'Texte court',textarea:'Texte long',number:'Nombre',date:'Date',select:'Liste de choix',checkbox:'Case à cocher'};
  const tabs=[['theme','Couleurs','grid'],['texts','Identité & textes','file'],['navigation','Navigation','menu'],['fields','Champs métier','layers'],['forms','Formulaire','file'],['pages','Pages & blocs','grid'],['versions','Publications','history']];
  let tab='theme',draft=null,working=null,dirty=false,versions=[],loading=false,pageIndex=0,seq=0;
  const clone=x=>structuredClone(x);
  const can=p=>(state.context?.permissions||[]).includes(p);
  const edit=()=>can('site.edit');
  const uid=prefix=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  const input=(label,path,value='',extra='')=>`<label class="form-field">${esc(label)}<input data-site-path="${esc(path)}" value="${esc(value)}" ${extra} ${edit()?'':'disabled'}></label>`;
  const textarea=(label,path,value='',extra='')=>`<label class="form-field">${esc(label)}<textarea data-site-path="${esc(path)}" ${extra} ${edit()?'':'disabled'}>${esc(value)}</textarea></label>`;
  const check=(label,path,value)=>`<label class="v2-check"><input type="checkbox" data-site-path="${esc(path)}" ${value?'checked':''} ${edit()?'':'disabled'}><span>${esc(label)}</span></label>`;
  const select=(label,path,value,options)=>`<label class="form-field">${esc(label)}<select data-site-path="${esc(path)}" ${edit()?'':'disabled'}>${Object.entries(options).map(([key,name])=>`<option value="${esc(key)}" ${String(value)===key?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
  const action=(key,label,icon='plus',extra='')=>`<button class="button small" data-designer-action="${key}" ${extra} ${edit()?'':'disabled'}>${ico(icon)}${label}</button>`;
  const error=err=>`<div class="form-error" role="alert">${esc(err.message||err)}</div>`;
  function markDirty(){dirty=true;const badge=$('#designer-save-state');if(badge){badge.className='v2-dirty';badge.textContent='Modifications non enregistrées';}const button=$('[data-designer-action="publish"]');if(button)button.disabled=true;}
  function pathSet(path,value){const parts=path.split('.');let target=working;for(const key of parts.slice(0,-1))target=target[key];target[parts.at(-1)]=value;markDirty();}
  function pathGet(path){return path.split('.').reduce((o,k)=>o?.[k],working);}
  function move(path,index,delta){const array=pathGet(path),target=index+delta;if(!Array.isArray(array)||target<0||target>=array.length)return;[array[index],array[target]]=[array[target],array[index]];markDirty();renderBody();}
  function orderButtons(path,index,length,removeAction=''){return `<div class="v2-editor-actions"><button class="icon-button" aria-label="Déplacer vers le haut" data-site-order="${esc(path)}" data-index="${index}" data-delta="-1" ${index===0||!edit()?'disabled':''}>↑</button><button class="icon-button" aria-label="Déplacer vers le bas" data-site-order="${esc(path)}" data-index="${index}" data-delta="1" ${index===length-1||!edit()?'disabled':''}>↓</button>${removeAction?`<button class="icon-button" aria-label="Retirer cet élément" data-designer-action="${removeAction}" data-index="${index}" ${edit()?'':'disabled'}>${ico('close')}</button>`:''}</div>`;}
  async function render(){
    $('#main').innerHTML=`<div class="page-heading"><div><div class="eyebrow">Conception du site</div><h1>Votre Vigie, à votre image</h1><p>Préparez les changements, prévisualisez-les, puis publiez une version.</p></div><div class="v2-toolbar"><button class="button" data-designer-action="preview">${ico('external')}Aperçu</button>${edit()?'<button class="button" data-designer-action="save">Enregistrer le brouillon</button>':''}${can('site.publish')?'<button class="button primary" data-designer-action="publish">Publier</button>':''}</div></div><div class="v2-editor-status"><span id="designer-save-state">Chargement du brouillon…</span></div><div id="designer-error"></div><div class="v2-designer"><nav class="v2-designer-nav" aria-label="Sections du concepteur">${tabs.map(([id,label,icon])=>`<button data-designer-tab="${id}" class="${tab===id?'active':''}">${ico(icon)}${label}</button>`).join('')}</nav><div id="designer-content" class="v2-designer-content"><div class="v2-empty">Chargement…</div></div></div>`;
    if(working){renderBody();return;}await load();
  }
  async function load(){loading=true;const request=++seq;try{const response=await api('/api/site/draft');if(request!==seq)return;draft=response;working=clone(response.config);dirty=false;pageIndex=0;renderBody();}catch(err){if($('#designer-error'))$('#designer-error').innerHTML=error(err);}finally{loading=false;}}
  function renderBody(){if(!working||!$('#designer-content'))return;$$('[data-designer-tab]').forEach(b=>b.classList.toggle('active',b.dataset.designerTab===tab));const save=$('#designer-save-state');if(save){save.className=dirty?'v2-dirty':'v2-revision-note';save.textContent=dirty?'Modifications non enregistrées':`Brouillon version ${draft.version}${draft.updated_at?` · ${dateFull(draft.updated_at)}`:''}`;}const publish=$('[data-designer-action="publish"]');if(publish)publish.disabled=dirty;if($('#designer-error'))$('#designer-error').innerHTML='';
    if(tab==='theme')themeView();if(tab==='texts')textsView();if(tab==='navigation')navigationView();if(tab==='fields')fieldsView();if(tab==='forms')formsView();if(tab==='pages')pagesView();if(tab==='versions')versionsView();
  }
  function themeView(){const labels={canvas:'Fond de l’application',surface:'Surfaces et cartes',ink:'Texte principal',muted:'Texte secondaire',nav:'Barre de navigation',accent:'Couleur d’action'};$('#designer-content').innerHTML=`<section class="v2-editor-section"><h3>Une palette confortable et lisible</h3><p>Les contrastes sont vérifiés à l’enregistrement. Les statuts métier conservent leurs couleurs de repérage.</p><div class="v2-grid">${Object.entries(labels).map(([key,label])=>`<label class="form-field">${label}<div class="v2-color-field"><input type="color" data-site-color="theme.${key}" value="${esc(working.theme[key])}" aria-label="Choisir ${label.toLowerCase()}" ${edit()?'':'disabled'}><input data-site-path="theme.${key}" value="${esc(working.theme[key])}" pattern="#[0-9a-fA-F]{6}" maxlength="7" aria-label="Code hexadécimal ${label.toLowerCase()}" ${edit()?'':'disabled'}></div></label>`).join('')}</div><div class="report-note" style="margin-top:23px">Le texte principal et secondaire doit rester lisible sur les fonds. Les boutons utilisent un libellé blanc ; la navigation utilise des libellés clairs.</div></section><section class="v2-editor-section" style="margin-top:18px"><h3>Prévisualiser les changements</h3><p>L’aperçu applique votre brouillon uniquement à cette session. Les autres utilisateurs voient toujours la version publiée.</p><button class="button" data-designer-action="preview">${ico('external')}Ouvrir l’aperçu du site</button></section>`;}
  function textsView(){$('#designer-content').innerHTML=`<section class="v2-editor-section"><h3>Identité de l’application</h3><p>Des textes simples, repris dans l’en-tête et les écrans de travail.</p><div class="v2-form-stack"><div class="v2-grid">${input('Nom du site','brand.name',working.brand.name,'maxlength="60" required')}${input('Signature','brand.tagline',working.brand.tagline,'maxlength="140"')}</div>${input('Titre de la liste des demandes','labels.requests_title',working.labels.requests_title,'maxlength="120" required')}${textarea('Description de la liste','labels.requests_subtitle',working.labels.requests_subtitle,'maxlength="500"')}${input('Bouton de création','labels.new_request',working.labels.new_request,'maxlength="100" required')}</div></section>`;}
  function navigationView(){working.navigation||=[];$('#designer-content').innerHTML=`<section class="v2-editor-section"><h3>Ordre et libellés de la navigation</h3><p>Masquer une entrée modifie la présentation. Les autorisations restent définies dans les rôles.</p><div class="v2-editor-list">${working.navigation.map((item,i)=>`<div class="v2-editor-item"><div class="v2-title-row"><strong>${esc(navLabels[item.key]||item.key)}</strong>${orderButtons('navigation',i,working.navigation.length)}</div><div class="v2-form-inline">${input('Libellé affiché',`navigation.${i}.label`,item.label,'maxlength="100" required')}${check('Visible dans le menu',`navigation.${i}.visible`,item.visible)}</div></div>`).join('')}</div></section>`;}
  function fieldsView(){working.request_fields||=[];const published=new Set((state.context.site?.config?.request_fields||[]).map(f=>f.key));$('#designer-content').innerHTML=`<section class="v2-editor-section"><div class="v2-title-row"><div><h3>Champs personnalisés des demandes</h3><p class="v2-hint">Les valeurs sont enregistrées avec la demande et contrôlées côté serveur.</p></div>${action('add-field','Ajouter un champ')}</div><div class="v2-editor-list">${working.request_fields.map((f,i)=>`<article class="v2-editor-item"><div class="v2-title-row"><h4>${esc(f.label||'Nouveau champ')} ${f.active===false?'<span class="badge status-closed">Retiré</span>':''}</h4>${orderButtons('request_fields',i,working.request_fields.length)}</div><div class="v2-grid">${input('Libellé',`request_fields.${i}.label`,f.label,'maxlength="120" required')}${input('Clé stable',`request_fields.${i}.key`,f.key,`pattern="cf_[a-z0-9_]+" maxlength="64" ${published.has(f.key)?'disabled':''}`)}<label class="form-field">Type<select data-site-path="request_fields.${i}.type" ${!edit()||published.has(f.key)?'disabled':''}>${Object.entries(types).map(([key,label])=>`<option value="${key}" ${f.type===key?'selected':''}>${label}</option>`).join('')}</select></label>${f.type==='select'?textarea('Choix proposés (un par ligne)',`request_fields.${i}.options`,(f.options||[]).join('\n'),'data-site-lines="true"'):''}</div><div class="v2-toolbar" style="margin-top:15px">${check('Champ actif',`request_fields.${i}.active`,f.active!==false)}${check('Obligatoire à la saisie',`request_fields.${i}.required`,f.required)}</div><p class="v2-hint" style="margin-top:11px">${published.has(f.key)?'La clé et le type sont conservés après publication. Retirer le champ masque sa saisie et conserve les valeurs historiques.':'La clé doit commencer par cf_ et contenir seulement des lettres minuscules, chiffres et tirets bas.'}</p></article>`).join('')||'<p class="v2-empty">Ajoutez les informations métier propres à votre équipe.</p>'}</div></section>`;}
  function formsView(){working.form_layout||=['title','channel'];const activeCustom=(working.request_fields||[]).filter(f=>f.active!==false);const available={...nativeFields,...Object.fromEntries(activeCustom.map(f=>[f.key,f.label]))};const used=new Set(working.form_layout);$('#designer-content').innerHTML=`<section class="v2-editor-section"><h3>Composer le formulaire de demande</h3><p>L’intitulé et le canal restent présents. Les autres champs peuvent être ordonnés ou retirés de la présentation. Les permissions déterminent les champs modifiables.</p><div class="v2-editor-list">${working.form_layout.map((key,i)=>`<div class="v2-editor-item"><div class="v2-title-row" style="margin:0"><div><strong>${esc(available[key]||key)}</strong>${['title','channel'].includes(key)?'<small class="muted"> · essentiel</small>':''}</div>${orderButtons('form_layout',i,working.form_layout.length,['title','channel'].includes(key)?'':'remove-layout')}</div></div>`).join('')}</div><div class="v2-form-inline" style="margin-top:20px"><label class="form-field">Ajouter un champ au formulaire<select id="site-add-layout" ${edit()?'':'disabled'}>${Object.entries(available).filter(([key])=>!used.has(key)).map(([key,label])=>`<option value="${esc(key)}">${esc(label)}</option>`).join('')}</select></label>${action('add-layout','Ajouter au formulaire')}</div><p class="v2-hint" style="margin-top:15px">Les champs personnalisés actifs absents de cette liste restent accessibles dans les informations complémentaires.</p></section>`;}
  function pagesView(){working.pages||=[];if(pageIndex>=working.pages.length)pageIndex=Math.max(0,working.pages.length-1);const page=working.pages[pageIndex];const roles=state.context.roles||[{id:'reader',name:'Lecteur'},{id:'contributor',name:'Contributeur'},{id:'manager',name:'Responsable'},{id:'admin',name:'Administrateur'}];$('#designer-content').innerHTML=`<section class="v2-editor-section"><div class="v2-title-row"><div><h3>Pages de votre espace</h3><p class="v2-hint">Contenus, liens, indicateurs et listes de demandes.</p></div>${action('add-page','Ajouter une page')}</div>${working.pages.length?`<div class="v2-tabs">${working.pages.map((p,i)=>`<button class="v2-tab ${pageIndex===i?'active':''}" data-site-page="${i}">${esc(p.name||'Nouvelle page')}</button>`).join('')}</div>`:''}${page?`<div class="v2-form-stack"><div class="v2-grid">${input('Nom de la page',`pages.${pageIndex}.name`,page.name,'maxlength="100" required')}${input('Adresse de la page',`pages.${pageIndex}.slug`,page.slug,'pattern="[a-z][a-z0-9-]*" maxlength="64" required')}</div><fieldset class="v2-permission-group"><legend>Rôles autorisés</legend><p class="v2-hint" style="margin-bottom:12px">Aucune sélection : tous les comptes connectés. Les données métier restent limitées au périmètre de chaque personne.</p><div class="v2-check-grid">${roles.map(r=>`<label class="v2-check"><input type="checkbox" data-site-audience="${esc(r.id)}" ${(page.audience_roles||[]).includes(r.id)?'checked':''} ${edit()?'':'disabled'}><span>${esc(r.name)}</span></label>`).join('')}</div></fieldset><div class="v2-title-row"><h3>Blocs de contenu</h3><div class="v2-toolbar"><select id="site-add-block" aria-label="Type de bloc" ${edit()?'':'disabled'}><option value="text">Texte</option><option value="table">Liste de demandes</option><option value="metrics">Indicateurs</option><option value="links">Liens</option></select>${action('add-block','Ajouter')}</div></div><div class="v2-editor-list">${(page.blocks||[]).map((block,i)=>blockEditor(block,i)).join('')||'<p class="v2-empty">Ajoutez un premier bloc pour composer cette page.</p>'}</div><div class="v2-toolbar">${action('preview-page','Prévisualiser cette page','external')}${action('remove-page','Retirer cette page','close')}</div></div>`:'<p class="v2-empty">Créez une page pour partager un guide, des liens utiles ou un tableau de suivi.</p>'}</section>`;}
  function blockEditor(b,index){const path=`pages.${pageIndex}.blocks.${index}`;return `<article class="v2-editor-item"><div class="v2-title-row"><h4>${({text:'Texte',table:'Liste de demandes',metrics:'Indicateurs',links:'Liens'})[b.type]}</h4>${orderButtons(`pages.${pageIndex}.blocks`,index,working.pages[pageIndex].blocks.length,'remove-block')}</div><div class="v2-form-stack">${input('Titre du bloc',`${path}.title`,b.title,'maxlength="150"')}${b.type==='text'?textarea('Texte',`${path}.text`,b.text,'rows="5" maxlength="20000"'):''}${b.type==='table'?`<div class="v2-grid">${select('Vue de demandes',`${path}.view`,b.view,Object.fromEntries(Object.entries(navLabels).filter(([key])=>!['reporting','imports'].includes(key))))}${input('Nombre maximal de lignes',`${path}.limit`,b.limit,'type="number" min="1" max="100"')}</div><p class="v2-hint">Chaque personne voit uniquement les demandes de son périmètre.</p>`:''}${b.type==='metrics'?`<div class="v2-check-grid">${Object.entries({total:'Total',active:'Actives',waiting:'En attente',unassigned:'Sans affectation',alerts:'Réponses à examiner',closed:'Closes'}).map(([key,label])=>`<label class="v2-check"><input type="checkbox" data-site-metric="${key}" data-block="${index}" ${(b.metrics||[]).includes(key)?'checked':''} ${edit()?'':'disabled'}><span>${label}</span></label>`).join('')}</div>`:''}${b.type==='links'?`<div class="v2-editor-list">${(b.links||[]).map((link,j)=>`<div class="v2-form-inline">${input('Libellé',`${path}.links.${j}.label`,link.label,'maxlength="150"')}${input('Adresse',`${path}.links.${j}.url`,link.url,'placeholder="https://… ou /…" maxlength="2000"')}<button class="icon-button" data-site-remove-link="${index}:${j}" aria-label="Retirer ce lien" ${edit()?'':'disabled'}>${ico('close')}</button></div>`).join('')}</div><button class="button small" data-site-add-link="${index}" ${edit()?'':'disabled'}>Ajouter un lien</button>`:''}</div></article>`;}
  async function versionsView(){$('#designer-content').innerHTML='<div class="v2-empty">Chargement des publications…</div>';try{const response=await api('/api/site/versions');versions=response.items||[];if(tab!=='versions'||!$('#designer-content'))return;$('#designer-content').innerHTML=`<section class="v2-editor-section"><h3>Historique des publications</h3><p>Restaurer une version la copie dans un nouveau brouillon. Une publication explicite reste nécessaire pour la rendre visible.</p><div class="v2-editor-list">${versions.map(v=>`<div class="v2-editor-item"><div class="v2-title-row" style="margin:0"><div><strong>Version ${v.version}</strong><p class="v2-revision-note">${esc(dateFull(v.published_at))} · ${esc(v.actor_name||'Administrateur')}</p></div><button class="button small" data-site-restore="${v.version}" ${edit()?'':'disabled'}>Restaurer en brouillon</button></div></div>`).join('')||'<p class="v2-empty">Aucune publication enregistrée.</p>'}</div></section>`;}catch(err){if($('#designer-content'))$('#designer-content').innerHTML=error(err);}}
  async function save(){if(!edit())return;const submitted=clone(working),serialized=JSON.stringify(submitted);const button=$('[data-designer-action="save"]');if(button)button.disabled=true;try{draft=await api('/api/site/draft',{method:'PATCH',body:{config:submitted,version:draft.version}});if(JSON.stringify(working)===serialized){working=clone(draft.config);dirty=false;}else dirty=true;renderBody();toast('Le brouillon a été enregistré.');}catch(err){if($('#designer-error'))$('#designer-error').innerHTML=`${error(err)}${err.status===409?'<button class="button small" data-designer-action="reload">Recharger le brouillon du serveur</button>':''}`;else toast(err.message,true);}finally{if(button?.isConnected)button.disabled=false;}}
  function publishModal(){if(dirty){toast('Enregistrez le brouillon avant de le publier.',true);return;}openModal({title:'Publier les changements',subtitle:`Brouillon version ${draft.version} · ${working.brand.name}`,content:`<form id="site-publish-form" class="modal-content"><p>Cette version sera appliquée uniquement à votre démonstration dans cet onglet. Les autres visiteurs ne verront pas vos essais.</p><div class="modal-note">${working.pages.length} page${working.pages.length>1?'s':''} · ${working.request_fields.filter(f=>f.active!==false).length} champ${working.request_fields.filter(f=>f.active!==false).length>1?'s':''} personnalisé${working.request_fields.filter(f=>f.active!==false).length>1?'s':''} actif${working.request_fields.filter(f=>f.active!==false).length>1?'s':''}. La version précédente reste disponible dans l’historique.</div><div id="site-modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="site-publish-form">Publier cette version</button>'});}
  function restoreModal(version){openModal({title:`Restaurer la version ${version}`,subtitle:'La version restaurée devient un nouveau brouillon.',content:`<form id="site-restore-form" data-version="${version}" class="modal-content"><p>${dirty?'Vos modifications non enregistrées seront remplacées. ':''}Les valeurs métier déjà saisies dans les demandes sont conservées. Les champs plus récents absents de cette version seront retirés du formulaire.</p><div id="site-modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="site-restore-form">Restaurer le brouillon</button>'});}
  async function click(event){const b=event.target.closest('button');if(!b)return;if(b.dataset.designerTab){tab=b.dataset.designerTab;renderBody();return;}if(b.dataset.sitePage!==undefined){pageIndex=Number(b.dataset.sitePage);renderBody();return;}if(b.dataset.siteRestore){restoreModal(Number(b.dataset.siteRestore));return;}if(b.dataset.siteOrder){move(b.dataset.siteOrder,Number(b.dataset.index),Number(b.dataset.delta));return;}if(b.dataset.siteAddLink!==undefined&&edit()){working.pages[pageIndex].blocks[Number(b.dataset.siteAddLink)].links.push({label:'Nouveau lien',url:'https://'});markDirty();renderBody();return;}if(b.dataset.siteRemoveLink&&edit()){const [i,j]=b.dataset.siteRemoveLink.split(':').map(Number);working.pages[pageIndex].blocks[i].links.splice(j,1);markDirty();renderBody();return;}
    const act=b.dataset.designerAction;if(!act)return;if(loading||!working){toast('Le brouillon est en cours de chargement.');return;}
    if(act==='save'){await save();return;}if(act==='publish'){publishModal();return;}if(act==='preview'||act==='preview-page'){env.activatePreview(clone(working),act==='preview-page'?`page:${working.pages[pageIndex].slug}`:null);return;}if(act==='reload'){if(dirty&&!confirm('Recharger remplace les modifications non enregistrées. Continuer ?'))return;await load();return;}if(!edit())return;
    if(act==='add-field'){const key=`cf_champ_${Date.now().toString(36)}`;working.request_fields.push({key,label:'Nouveau champ',type:'text',options:[],required:false,active:true});}
    if(act==='add-layout'){const key=$('#site-add-layout')?.value;if(key)working.form_layout.push(key);else return;}
    if(act==='remove-layout'){working.form_layout.splice(Number(b.dataset.index),1);}
    if(act==='add-page'){const id=uid('page');working.pages.push({id,slug:id,name:'Nouvelle page',audience_roles:[],blocks:[]});pageIndex=working.pages.length-1;}
    if(act==='remove-page'){if(!confirm('Retirer cette page du brouillon ? La version publiée reste disponible.'))return;working.pages.splice(pageIndex,1);pageIndex=0;}
    if(act==='add-block'){const type=$('#site-add-block').value;const block={id:uid('bloc'),type,title:''};if(type==='text')block.text='';if(type==='table')Object.assign(block,{view:'active',limit:20});if(type==='metrics')block.metrics=['active','waiting'];if(type==='links')block.links=[];working.pages[pageIndex].blocks.push(block);}
    if(act==='remove-block')working.pages[pageIndex].blocks.splice(Number(b.dataset.index),1);
    markDirty();renderBody();
  }
  document.addEventListener('click',event=>click(event).catch(err=>toast(err.message,true)));
  document.addEventListener('input',event=>{const el=event.target;if(!working||!edit())return;if(el.dataset.siteColor){pathSet(el.dataset.siteColor,el.value);const text=$(`[data-site-path="${el.dataset.siteColor}"]`);if(text)text.value=el.value;}if(el.dataset.sitePath&&el.type!=='checkbox'&&el.tagName!=='SELECT'){let value=el.value;if(el.dataset.siteLines)value=value.split('\n').map(v=>v.trim()).filter(Boolean);else if(el.type==='number')value=Number(value);pathSet(el.dataset.sitePath,value);if(el.dataset.sitePath.startsWith('theme.')&&/^#[a-f0-9]{6}$/i.test(value)){const color=$(`[data-site-color="${el.dataset.sitePath}"]`);if(color)color.value=value;}}});
  document.addEventListener('change',event=>{const el=event.target;if(!working||!edit())return;if(el.dataset.sitePath&&(el.type==='checkbox'||el.tagName==='SELECT')){pathSet(el.dataset.sitePath,el.type==='checkbox'?el.checked:el.value);if(el.dataset.sitePath.endsWith('.type'))renderBody();}if(el.dataset.siteAudience){const p=working.pages[pageIndex];p.audience_roles=el.checked?[...new Set([...(p.audience_roles||[]),el.dataset.siteAudience])]:(p.audience_roles||[]).filter(r=>r!==el.dataset.siteAudience);markDirty();}if(el.dataset.siteMetric){const b=working.pages[pageIndex].blocks[Number(el.dataset.block)];b.metrics=el.checked?[...new Set([...(b.metrics||[]),el.dataset.siteMetric])]:(b.metrics||[]).filter(m=>m!==el.dataset.siteMetric);markDirty();}});
  document.addEventListener('submit',async event=>{const f=event.target;if(!['site-publish-form','site-restore-form'].includes(f.id))return;event.preventDefault();const button=$(`[form="${f.id}"][type="submit"]`);if(button)button.disabled=true;try{if(f.id==='site-publish-form'){await api('/api/site/publish',{method:'POST',body:{version:draft.version}});closeModal();dirty=false;working=null;await env.refreshSite();toast('La nouvelle version du site est publiée.');await load();}else{draft=await api('/api/site/restore',{method:'POST',body:{version:Number(f.dataset.version),draft_version:draft.version}});working=clone(draft.config);dirty=false;closeModal();tab='theme';renderBody();toast('La version a été restaurée en brouillon.');}}catch(err){if($('#site-modal-error'))$('#site-modal-error').innerHTML=error(err);else toast(err.message,true);}finally{if(button?.isConnected)button.disabled=false;}});
  return {render,isDirty:()=>dirty,reset:()=>{draft=null;working=null;dirty=false;seq++;},getConfig:()=>working};
}
