import {createAdminUI} from './admin.js';
import {createDesigner} from './designer.js';

export function createV2(env){
  const {state,api,$,$$,esc,ico,toast,openModal,closeModal,dateFull,num,boot,navigate,renderShell,openDetail,download}=env;
  let auth=null,preview=null,expiredPending=false,pageSeq=0;
  const can=permission=>(state.context?.permissions||state.context?.actor?.permissions||[]).includes(permission);
  const config=()=>preview||state.context?.site?.config||{};
  const nativeLabels={title:'Intitulé',channel:'Canal',requester:'Demandeur',requester_email:'E-mail du demandeur',description:'Description',priority:'Priorité',application:'Application',category:'Catégorie',environment:'Environnement',ritm:'RITM',assignee:'Affectation',status:'Statut'};
  const scopeName=value=>({own:'Mes demandes',team:'Mes équipes',all:'Toutes les demandes'})[value]||value;
  const opts=(items,value='',empty='Non renseigné')=>`${value&&!(items||[]).some(item=>String(typeof item==='string'?item:item.id)===String(value))?`<option value="${esc(value)}" selected>${esc(value)} (ancienne valeur)</option>`:''}${empty!==null?`<option value="">${esc(empty)}</option>`:''}${(items||[]).map(item=>{const key=typeof item==='string'?item:item.id;const label=typeof item==='string'?item:item.name;return `<option value="${esc(key)}" ${String(key)===String(value)?'selected':''}>${esc(label)}</option>`;}).join('')}`;
  const error=err=>`<div class="form-error" role="alert">${esc(err.message||err)}</div>`;
  const designer=createDesigner({...env,activatePreview,refreshSite});
  const admin=createAdminUI(env);
  async function ensureAuth(){auth=await api('/api/auth/state');state.context={...(state.context||{}),csrf_token:auth.csrf_token};if(!auth.authenticated){renderAuth();return false;}return true;}
  function renderAuth(message=''){
    preview=null;document.documentElement.classList.remove('site-preview');document.body.style.overflow='';$('#overlay-root').replaceChildren();$('#site-preview-banner')?.remove();const setup=auth?.setup_required;
    $('#app').innerHTML=`<main class="v2-auth"><section class="v2-auth-intro"><div class="brand"><span class="brand-symbol">V</span><div><div class="brand-name">vigie<span class="brand-accent">.</span></div><div class="brand-caption">Le suivi, en clair</div></div></div><div><h1>Chaque demande.<br>Chaque échange.<br><span>Une même vue.</span></h1><p>Un espace de travail pour suivre les sollicitations SAP RIP, partager leur traitement et retrouver les décisions prises.</p></div><div class="v2-auth-foot">Comptes Vigie · données de cette installation<br>Outlook et l’identité d’entreprise ne sont pas connectés.</div></section><section class="v2-auth-main"><div class="v2-auth-card"><div class="eyebrow">${setup?'Première ouverture':'Votre espace de travail'}</div><h2>${setup?'Créer le premier administrateur':'Se connecter à Vigie'}</h2><p>${setup?'Ce compte permettra de configurer les accès, les équipes et le site.':'Retrouvez les demandes accessibles à votre compte.'}</p><form id="vigie-auth-form" class="v2-auth-form" data-setup="${setup?'true':'false'}">${setup?'<label class="form-field">Votre nom<input name="name" required maxlength="150" autocomplete="name" placeholder="Prénom Nom"></label>':''}<label class="form-field">Identifiant<input name="username" required maxlength="100" autocomplete="username" spellcheck="false" autocapitalize="none" placeholder="prenom.nom"></label><label class="form-field">Mot de passe<input name="password" type="password" required ${setup?'minlength="12"':''} autocomplete="${setup?'new-password':'current-password'}"></label>${setup?'<label class="form-field">Confirmer le mot de passe<input name="confirm_password" type="password" required minlength="12" autocomplete="new-password"></label><p class="v2-hint">Au moins 12 caractères. Choisissez un mot de passe propre à Vigie.</p>':''}<div id="auth-error">${message?error(message):''}</div><button class="button primary" type="submit">${ico(setup?'shield':'lock')}${setup?'Créer mon compte administrateur':'Se connecter'}</button></form><p class="v2-auth-note">${setup?'Les demandes existantes sont conservées. Vous pourrez créer les comptes de votre équipe depuis l’administration.':'Besoin d’un compte ou d’un nouveau mot de passe ? Contactez votre administrateur Vigie.'}</p></div></section></main>`;
    $('input[name="username"]')?.focus();
  }
  async function expired(){if(expiredPending)return;expiredPending=true;state.workspaceSeq++;state.listSeq++;state.detail=null;state.detailId=null;state.detailDirty=false;state.stats={};state.items=[];state.total=0;state.selected.clear();pageSeq++;designer.reset();try{auth=await api('/api/auth/state');state.context={...(state.context||{}),csrf_token:auth.csrf_token};renderAuth('Votre session a expiré ou a été révoquée. Reconnectez-vous pour continuer.');}catch{renderAuth('La session est terminée. Rechargez la page pour vous reconnecter.');}finally{expiredPending=false;}}
  async function logout(){try{await api('/api/auth/logout',{method:'POST',body:{}});}catch(err){if(err.status!==401){toast(err.message,true);return;}}state.workspaceSeq++;state.listSeq++;state.detail=null;state.detailId=null;state.detailDirty=false;state.stats={};state.items=[];state.total=0;state.selected.clear();pageSeq++;designer.reset();await ensureAuth();}
  function applyConfig(){const c=config();const allowed={canvas:'--canvas',surface:'--surface',ink:'--ink',muted:'--muted',nav:'--nav',accent:'--teal'};for(const [key,variable] of Object.entries(allowed)){const value=c.theme?.[key];if(/^#[a-f0-9]{6}$/i.test(value||''))document.documentElement.style.setProperty(variable,value);}document.title=`${c.brand?.name||'Vigie'} · Suivi des demandes SAP RIP`;const perms=state.context?.permissions||[];for(const key of ['requests.read','requests.create','requests.comment','requests.update','requests.assign','requests.status','requests.close','requests.reopen','requests.move','requests.import','requests.export','admin.backup'])document.documentElement.classList.toggle(`no-${key.replaceAll('.','-')}`,!perms.includes(key));document.documentElement.classList.toggle('no-import-scope',state.context?.actor?.scope!=='all');}
  function accessible(view){if(view==='admin')return ['admin.users','admin.roles','admin.logs'].some(can);if(view==='designer')return can('site.edit')||can('site.publish');if(view==='settings')return true;if(view.startsWith('page:'))return true;if(view==='imports')return can('requests.import')&&state.context?.actor?.scope==='all';return can('requests.read');}
  function defaultView(){if(can('requests.read'))return (config().navigation||[]).find(n=>n.visible&&accessible(n.key))?.key||'active';if(can('site.edit')||can('site.publish'))return 'designer';if(['admin.users','admin.roles','admin.logs'].some(can))return 'admin';const first=config().pages?.[0];return first?`page:${first.slug}`:'settings';}
  function acceptContext(){applyConfig();if(!accessible(state.view))state.view=defaultView();}
  function shell(){
    applyConfig();const c=config(),actor=state.context.actor;const brand=$('.brand-name');if(brand)brand.innerHTML=`${esc(c.brand?.name||'vigie')}<span class="brand-accent">.</span>`;if($('.brand-caption'))$('.brand-caption').textContent=c.brand?.tagline||'Le suivi, en clair';
    const footer=$('.sidebar-footer');if(footer)footer.innerHTML=`<div class="avatar">${esc(String(actor.name||'').split(/\s+/).slice(0,2).map(s=>s[0]).join(''))}</div><button class="v2-profile" data-v2-action="profile"><div class="actor-name">${esc(actor.name)}</div><div class="actor-role">${esc(actor.role_name||actor.role_id)}</div></button><button class="icon-button v2-logout" data-v2-action="logout" aria-label="Se déconnecter" title="Se déconnecter">${ico('external')}</button>`;
    const navigation=config().navigation||[];const firstNav=$('.sidebar nav');const secondary=$$('.sidebar nav')[1];for(const item of navigation){const button=$(`.sidebar [data-view="${item.key}"]`);if(!button)continue;button.hidden=!item.visible||!accessible(item.key);const text=$('.nav-text',button);if(text)text.textContent=item.label;firstNav?.append(button);}
    $$('.sidebar [data-view]').forEach(b=>{if(!accessible(b.dataset.view))b.hidden=true;});
    const extra=document.createElement('nav');extra.className='nav-group v2-nav';extra.setAttribute('aria-label','Pages et administration');extra.innerHTML=`${(c.pages||[]).filter(page=>actor.role_id==='admin'||!page.audience_roles?.length||page.audience_roles.includes(actor.role_id)).map(page=>`<button class="nav-item" data-view="page:${esc(page.slug)}">${ico('file')}<span class="nav-text">${esc(page.name)}</span></button>`).join('')}${['admin.users','admin.roles','admin.logs'].some(can)?`<button class="nav-item" data-view="admin">${ico('shield')}<span class="nav-text">Administration</span></button>`:''}${can('site.edit')||can('site.publish')?`<button class="nav-item" data-view="designer">${ico('grid')}<span class="nav-text">Concepteur du site</span></button>`:''}`;footer?.before(extra);
    const local=$('.local-status');if(local)local.innerHTML=`<span class="status-dot"></span>${esc(scopeName(actor.scope))}`;const source=$('#workspace-select option[value="local"]');if(source)source.textContent='Espace de travail · mes données';
    document.documentElement.classList.toggle('site-preview',Boolean(preview));if(preview)showPreviewBanner();
  }
  function decorate(root=document){
    const c=config();if(!['admin','designer','settings','imports','reporting'].includes(state.view)&&!state.view.startsWith('page:')){const title=$('#main h1');if(title)title.textContent=c.labels?.requests_title||'Demandes';const subtitle=$('#main .page-heading p');if(subtitle)subtitle.textContent=c.labels?.requests_subtitle||'Une vue unique pour suivre chaque sollicitation, du premier échange à la clôture.';}
    $$('[data-action="new"]',root).forEach(b=>{b.innerHTML=`${ico('plus')}${esc(c.labels?.new_request||'Nouvelle demande')}`;});
  }
  function route(view){if(view==='admin'){admin.render();return true;}if(view==='designer'){designer.render();return true;}if(view.startsWith('page:')){renderCustomPage(view.slice(5));return true;}if(view==='settings'){renderSettings();return true;}if(!accessible(view)){$('#main').innerHTML='<div class="empty-state"><h2>Accès limité</h2><p>Votre compte ne permet pas de consulter cette vue.</p></div>';return true;}return false;}
  function renderSettings(){const actor=state.context.actor;$('#main').innerHTML=`<div class="page-heading"><div><div class="eyebrow">Votre environnement</div><h1>Paramètres</h1><p>Identité, périmètre et services disponibles sur cette installation.</p></div></div><div class="settings-grid"><section class="settings-card">${ico('person')}<h3>Votre compte Vigie</h3><div class="setting-row"><span>Nom</span><strong>${esc(actor.name)}</strong></div><div class="setting-row"><span>Identifiant</span><strong>${esc(actor.username)}</strong></div><div class="setting-row"><span>Rôle</span><strong>${esc(actor.role_name||actor.role_id)}</strong></div><div class="setting-row"><span>Périmètre</span><strong>${esc(scopeName(actor.scope))}</strong></div><p style="margin-top:12px">Vos droits sont vérifiés pour chaque action et chaque demande. Les équipes de votre compte déterminent les demandes visibles avec le périmètre équipe.</p><button class="button" style="margin-top:15px" data-v2-action="logout">Se déconnecter</button></section><section class="settings-card">${ico('database')}<h3>Données & espaces</h3><p>La démonstration et l’espace de travail ont des données séparées. Les comptes, les équipes et le site sont communs à cette installation.</p><div class="setting-row"><span>Espace actif</span><strong>${state.workspace==='demo'?'Démonstration':'Espace de travail'}</strong></div>${can('admin.backup')?'<div class="v2-form-stack" style="margin-top:18px"><button class="button" data-v2-action="full-backup">Télécharger la sauvegarde complète</button><button class="download-link" data-action="backup">Sauvegarder uniquement cet espace</button><p class="v2-hint">La sauvegarde complète regroupe les demandes, les comptes et la configuration du site.</p></div>':''}</section><section class="settings-card">${ico('mail')}<h3>Messagerie et identité d’entreprise</h3><p>Les comptes sont gérés dans Vigie. Outlook et l’annuaire d’entreprise ne sont pas connectés. Les imports de fichiers restent accessibles aux personnes disposant du droit d’import et d’un périmètre global.</p><div class="tag-list"><span>Outlook non connecté</span><span>SSO non connecté</span></div></section><section class="settings-card">${ico('chart')}<h3>Reporting</h3><p>Les données de reporting respectent le périmètre de votre compte. Les exports sont réservés aux personnes autorisées.</p>${can('requests.export')?'<button class="download-link" style="margin-top:18px" data-action="report-export">Télécharger la source JSON</button>':''}</section></div>`;}
  function fieldHTML(key,request={},mode='create'){
    const creation=mode==='create',right=mode==='detail';const custom=(config().request_fields||[]).find(f=>f.key===key);let label=custom?.label||nativeLabels[key]||key,value=custom?request.custom_fields?.[key]:request[key]??'',name=key,type='text',control='';
    let disabled=!creation&&!can('requests.update');let required=creation&&['title','channel'].includes(key);
    if(custom){if(custom.active===false)return '';name=`custom:${key}`;required=Boolean(custom.required);value=value??(custom.type==='checkbox'?false:'');if(custom.type==='textarea')control=`<textarea name="${esc(name)}" maxlength="20000" ${required?'required':''} ${disabled?'disabled':''}>${esc(value)}</textarea>`;else if(custom.type==='select')control=`<select name="${esc(name)}" ${required?'required':''} ${disabled?'disabled':''}>${opts(custom.options||[],value,'Choisir…')}</select>`;else if(custom.type==='checkbox')return `<label class="v2-check" data-form-key="${key}"><input name="${esc(name)}" type="checkbox" ${value?'checked':''} ${disabled?'disabled':''}><span>${esc(label)}${required?' <span class="v2-required">*</span>':''}</span></label>`;else{type=custom.type==='number'?'number':custom.type==='date'?'date':'text';control=`<input name="${esc(name)}" type="${type}" ${type==='number'?'step="any"':''} value="${esc(value)}" ${required?'required':''} ${disabled?'disabled':''}>`;}}
    else if(key==='assignee'){name='assignee_id';value=request.assignee_id||(!creation&&request.assignee?'__legacy_assignee__':'');disabled=!creation&&!can('requests.assign');const users=[...(can('requests.assign')?state.context.users||[]:(state.context.users||[]).filter(u=>u.id===state.context.actor.id))];if(value&&!users.some(u=>u.id===value))users.push({id:value,name:request.assignee||'Affectation existante'});control=`<select name="${name}" ${disabled?'disabled':''}>${opts(users,value,'Non affectée')}</select>`;}
    else if(key==='status'){disabled=creation||!['requests.status','requests.close','requests.reopen'].some(can);value=request.status||'Ouvert';const choices=(state.context.statuses||[]).filter(status=>status===value||(value==='Clos'?can('requests.reopen'):status==='Clos'?can('requests.close'):can('requests.status')));control=`<select name="status" ${disabled?'disabled':''}>${opts(choices,value,null)}</select>`;}
    else if(['channel','priority','application','category','environment'].includes(key)){const optionKey={channel:'channels',priority:'priorities',application:'applications',category:'categories',environment:'environments'}[key];if(key==='priority'&&!value)value='Normale';if(key==='channel'&&!value)value=state.context.channels?.[0]||'Autre';control=`<select name="${key}" ${required?'required':''} ${disabled?'disabled':''}>${opts(state.context[optionKey]||[],value,['channel','priority'].includes(key)?null:'Non renseigné')}</select>`;}
    else if(key==='description')control=`<textarea name="description" rows="${creation?4:5}" maxlength="20000" ${disabled?'disabled':''}>${esc(value)}</textarea>`;
    else control=`<input name="${key}" value="${esc(value)}" type="${key==='requester_email'?'email':'text'}" maxlength="${key==='title'?300:254}" ${required?'required':''} ${disabled?'disabled':''}>`;
    return `<label class="form-field" data-form-key="${esc(key)}">${esc(label)}${required?' <span class="v2-required">*</span>':''}${control}${key==='ritm'?'<span class="field-hint">Facultatif</span>':''}${key==='assignee'&&request.assignee&&!request.assignee_id?`<span class="field-hint">Historique : ${esc(request.assignee)} · non lié à un compte</span>`:''}</label>`;
  }
  function fieldKeys(mode){const layout=config().form_layout||Object.keys(nativeLabels);let keys=[...new Set([...layout,...(config().request_fields||[]).filter(f=>f.active!==false).map(f=>f.key)])];if(mode==='detail')keys=keys.filter(k=>!['title','channel','requester','requester_email','description'].includes(k));if(mode==='identity')keys=keys.filter(k=>['title','channel','requester','requester_email','description'].includes(k));return keys;}
  function teamField(request={},mode='create'){if(!can('requests.assign'))return '';return `<label class="form-field">Équipe de suivi<select name="team_id">${opts(state.context.teams,request.team_id||state.context.actor.team_ids?.[0]||'general',null)}</select></label>`;}
  function newRequestModal(){if(!can('requests.create'))return;openModal({title:config().labels?.new_request||'Nouvelle demande',subtitle:'Les informations sont conservées dans une fiche unique.',wide:true,content:`<form id="new-request-form" class="modal-content"><div class="v2-form-stack">${fieldKeys('create').filter(k=>k!=='status').map(key=>fieldHTML(key,{},'create')).join('')}${teamField({},'create')}</div><div class="modal-note">La demande est créée avec le statut <strong>Ouvert</strong>. Le RITM reste facultatif.</div><div id="modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="new-request-form">Créer la demande</button>'});}
  function editIdentityModal(){if(!state.detail||!can('requests.update'))return;const request=state.detail.request;openModal({title:'Modifier la demande',subtitle:request.reference,wide:true,content:`<form id="edit-identity-form" class="modal-content">${fieldKeys('identity').map(key=>fieldHTML(key,request,'identity')).join('')}<div id="modal-error"></div></form>`,footer:'<button class="button" data-action="close-modal">Annuler</button><button class="button primary" type="submit" form="edit-identity-form">Enregistrer</button>'});}
  function retiredFields(request){const fields=(config().request_fields||[]).filter(f=>f.active===false&&Object.hasOwn(request.custom_fields||{},f.key));if(!fields.length)return '';return `<details class="v2-retired-fields"><summary>Champs retirés (${fields.length})</summary>${fields.map(f=>{const value=request.custom_fields[f.key];return `<div class="setting-row"><span>${esc(f.label)}</span><strong>${esc(typeof value==='boolean'?(value?'Oui':'Non'):value??'—')}</strong></div>`;}).join('')}</details>`;}
  function detailFields(request){const writable=['requests.update','requests.assign','requests.status','requests.close','requests.reopen'].some(can);return `<section class="detail-fields"><h3>Suivi de la demande</h3><form id="detail-form"><div class="form-fields">${fieldKeys('detail').map(key=>fieldHTML(key,request,'detail')).join('')}${teamField(request,'detail')}</div><div class="form-actions"><div id="detail-form-error"></div>${writable?`<button class="button primary" type="submit">${ico('check')}Enregistrer les modifications</button><small class="muted audit-caption">Modifications tracées dans l’historique</small>`:'<div class="v2-readonly-note">Consultation uniquement. Votre rôle ne permet pas de modifier le suivi.</div>'}</div></form></section>${retiredFields(request)}<div class="details-facts"><div class="fact-row"><span>Création</span><strong>${esc(dateFull(request.created_at))}</strong></div><div class="fact-row"><span>Dernière modification</span><strong>${esc(dateFull(request.updated_at))}</strong></div><div class="fact-row"><span>Échanges rattachés</span><strong>${num(request.message_count)} messages · ${num(request.reply_count)} réponses</strong></div><div class="fact-row"><span>Version de la fiche</span><strong>${num(request.version)}</strong></div></div>`;}
  function formData(form){const fd=new FormData(form),data=Object.fromEntries(fd),custom={};if(data.assignee_id==='__legacy_assignee__')delete data.assignee_id;for(const [name,value] of Object.entries(data)){if(name.startsWith('custom:')){const key=name.slice(7),def=(config().request_fields||[]).find(f=>f.key===key);custom[key]=def?.type==='number'?(value===''?null:Number(value)):value;delete data[name];}}for(const el of $$('input[type="checkbox"][name^="custom:"]:not([disabled])',form))custom[el.name.slice(7)]=el.checked;if(Object.keys(custom).length)data.custom_fields=custom;return data;}
  function detailDecorate(){const root=$('#detail-backdrop');if(!root)return;if(preview){$$('button[type="submit"]',root).forEach(b=>b.disabled=true);const fields=$('.detail-fields',root);if(fields)fields.insertAdjacentHTML('afterbegin','<div class="v2-readonly-note">Aperçu du formulaire : les données ne peuvent pas être modifiées ici.</div>');}if(!can('requests.comment'))$('#comment-form',root)?.remove();if(!can('requests.update'))$('[data-action="edit-identity"]',root)?.remove();if(!can('requests.move'))$$('[data-move-message]',root).forEach(b=>b.remove());if(!can('requests.reopen')&&!can('requests.update'))$('[data-action="review-alert"]',root)?.remove();}
  function reviewOptions(){const reopen=$('#review-alert-form input[value="reopen"]');if(reopen&&!can('requests.reopen')){reopen.disabled=true;reopen.checked=false;const keep=$('#review-alert-form input[value="keep"]');if(keep)keep.checked=true;}}
  async function refreshSite(){const context=await api('/api/context');state.context=context;preview=null;$('#site-preview-banner')?.remove();applyConfig();renderShell();}
  function activatePreview(value,target){preview=value;applyConfig();state.view=target||(!can('requests.read')&&value.pages?.length?`page:${value.pages[0].slug}`:defaultView());renderShell();showPreviewBanner();}
  function showPreviewBanner(){let bar=$('#site-preview-banner');if(!bar){bar=document.createElement('div');bar.id='site-preview-banner';bar.className='v2-preview-banner';document.body.prepend(bar);}bar.innerHTML='<span><strong>Aperçu du brouillon</strong> · lecture et formulaires uniquement · aucune donnée modifiée</span><div class="v2-toolbar"><button class="button small" data-v2-action="return-designer">Revenir au concepteur</button><button class="button small" data-v2-action="exit-preview">Quitter l’aperçu</button></div>';}
  function safeHref(value){if(typeof value!=='string')return null;if(/^\/[a-zA-Z0-9/_?=&.%#-]*$/.test(value)&&!value.startsWith('//'))return value;try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
  async function renderCustomPage(slug){const sequence=++pageSeq;$('#main').innerHTML='<div class="v2-empty" role="status">Chargement de la page…</div>';try{let page;if(preview){page=(preview.pages||[]).find(p=>p.slug===slug);}else{const response=await api(`/api/site/pages/${encodeURIComponent(slug)}`);page=response.page||response;}if(!page)throw new Error('Cette page n’est pas disponible pour votre rôle.');if(sequence!==pageSeq||state.view!==`page:${slug}`)return;
    $('#main').innerHTML=`<div class="page-heading"><div><div class="eyebrow">${esc(config().brand?.name||'Vigie')}</div><h1>${esc(page.name)}</h1></div></div><div class="v2-custom-page">${(page.blocks||[]).map((block,i)=>`<section class="v2-block" id="custom-block-${i}">${block.title?`<h2>${esc(block.title)}</h2>`:''}${block.type==='text'?`<p>${esc(block.text)}</p>`:block.type==='links'?`<div class="v2-block-links">${(block.links||[]).map(link=>{const url=safeHref(link.url);return url?`<a class="button" href="${esc(url)}" ${url.startsWith('/')?'':'target="_blank" rel="noopener noreferrer"'}>${ico('external')}${esc(link.label)}</a>`:'';}).join('')}</div>`:can('requests.read')?'<p class="muted" role="status">Chargement des données…</p>':'<p class="muted">Ce bloc de données nécessite un droit de consultation des demandes.</p>'}</section>`).join('')}</div>`;
    const results=await Promise.allSettled((page.blocks||[]).map(async(block,i)=>{if(!can('requests.read')||!['metrics','table'].includes(block.type))return;const data=await api(block.type==='metrics'?'/api/stats':`/api/requests?view=${encodeURIComponent(block.view||'active')}`);if(sequence!==pageSeq||state.view!==`page:${slug}`)return;const region=$(`#custom-block-${i}`);if(!region)return;const title=block.title?`<h2>${esc(block.title)}</h2>`:'';if(block.type==='metrics'){const labels={total:'Demandes',active:'Actives',waiting:'En attente',unassigned:'Sans affectation',alerts:'À examiner',closed:'Closes'};region.innerHTML=title+`<div class="v2-grid cols3">${(block.metrics||[]).map(metric=>`<div class="v2-card"><div class="muted">${labels[metric]||esc(metric)}</div><div class="stat-number">${num(data[metric])}</div></div>`).join('')}</div>`;}else{const items=(data.items||[]).slice(0,Number(block.limit)||20);region.innerHTML=title+(items.length?`<div class="table-wrap"><table><thead><tr><th>Référence</th><th>Demande</th><th>Statut</th><th>Affectation</th></tr></thead><tbody>${items.map(r=>`<tr><td>${esc(r.reference)}</td><td><button class="request-title-button" data-open="${r.id}">${esc(r.title)}</button></td><td>${esc(r.status)}</td><td>${esc(r.assignee||'Non affectée')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Aucune demande dans cette vue.</p>');}}));
    for(let i=0;i<results.length;i++)if(results[i].status==='rejected'){const region=$(`#custom-block-${i}`);if(region)region.innerHTML=error(results[i].reason);}
  }catch(err){if(sequence===pageSeq&&$('#main'))$('#main').innerHTML=error(err);}}
  function beforeNavigate(view){if(state.view==='designer'&&view!=='designer'&&designer.isDirty()&&!preview)return confirm('Le brouillon contient des modifications non enregistrées. Elles restent dans cette session. Quitter le concepteur ?');return true;}
  function profile(){const u=state.context.actor;openModal({title:u.name,subtitle:u.username,content:`<div class="modal-content"><div class="setting-row"><span>Rôle métier</span><strong>${esc(u.role_name||u.role_id)}</strong></div><div class="setting-row"><span>Périmètre</span><strong>${esc(scopeName(u.scope))}</strong></div><div class="tag-list">${u.site_edit?'<span>Conception du site</span>':''}${u.site_publish?'<span>Publication du site</span>':''}</div><p class="v2-hint">Les droits et les équipes de votre compte sont gérés par votre administrateur Vigie.</p></div>`,footer:'<button class="button" data-action="close-modal">Fermer</button><button class="button" data-v2-action="logout">Se déconnecter</button>'});}
  document.addEventListener('click',event=>{const anchor=event.target.closest('a[href]');if(anchor){const href=anchor.getAttribute('href');if(href?.startsWith('/')&&!href.startsWith('//')){const slug=href.split(/[?#]/)[0].replace(/^\//,'').replace(/^p\//,'');const page=(config().pages||[]).find(p=>p.slug===slug);if(page){event.preventDefault();navigate(`page:${page.slug}`);return;}}}const b=event.target.closest('[data-v2-action]');if(!b)return;const run=async()=>{switch(b.dataset.v2Action){case'logout':await logout();break;case'profile':profile();break;case'full-backup':await download('/api/admin/backup','vigie-sauvegarde-complete.zip');break;case'return-designer':state.view='designer';renderShell();break;case'exit-preview':preview=null;$('#site-preview-banner')?.remove();applyConfig();state.view='designer';renderShell();break;}};run().catch(err=>toast(err.message,true));});
  document.addEventListener('submit',async event=>{const f=event.target;if(f.id!=='vigie-auth-form')return;event.preventDefault();const data=Object.fromEntries(new FormData(f)),setup=f.dataset.setup==='true';$('#auth-error').innerHTML='';if(setup&&data.password!==data.confirm_password){$('#auth-error').innerHTML=error('Les deux mots de passe ne correspondent pas.');return;}const button=$('button[type="submit"]',f);button.disabled=true;try{delete data.confirm_password;const response=await api(setup?'/api/auth/setup':'/api/auth/login',{method:'POST',body:data});state.context={...(state.context||{}),csrf_token:response.csrf_token};state.view='active';state.stats={};state.items=[];state.total=0;state.selected.clear();state.filters={q:'',status:'',assignee:'',priority:'',source:'',application:'',category:'',from:'',to:'',sort:'updated_desc'};await boot();}catch(err){if($('#auth-error'))$('#auth-error').innerHTML=error(err);}finally{if(button.isConnected)button.disabled=false;}});
  window.addEventListener('beforeunload',event=>{if(designer.isDirty()){event.preventDefault();event.returnValue='';}});
  return {ensureAuth,expired,can,config,acceptContext,shell,decorate,route,detailFields,newRequestModal,editIdentityModal,formData,detailDecorate,reviewOptions,beforeNavigate,assigneeOptions:(value)=>opts(state.context.users,value,'Toutes les affectations'),isPreview:()=>Boolean(preview),reset:()=>designer.reset()};
}
